---
title: "Old Faithful Iris"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(ggplot2)
```

```{r read-data, echo=FALSE}
df <- iris
no_species <- df %>%
  select(Species) %>%
  unique() %>%
# Count() returns a df and I want an integer. So I use nrow()
  nrow()
```

Page 1
====================================

Row {data-height=70}
-----------------------------------------------------------------------
### Sample size

```{r valueboxes_size}
valueBox(nrow(df), caption = "Specimens measured", color = "orchid", icon = "ion-ios-flower")
```

### Species

```{r valueboxes_spec}
valueBox(no_species, caption = "Species collected", color = "orchid", icon = "fa-solid fa-heart")
```

### Sepal status

``` {r}
gauge(mean(df$Sepal.Length, na.rm = T), min=min(df$Sepal.Length, na.rm = T), max=max(df$Sepal.Length, na.rm = T), 
      symbol = "Millimeters", 
      gaugeSectors(success = c(6.4,7.9),
                   warning = c(5.2,6.3), 
                   danger = c(4,5.1)
                   )
      )
```

Row {data-height=100}
-----------------------------------------------------------------------
Iris is a flowering plant genus of 310 accepted species with showy flowers. As well as being the scientific name, iris is also widely used as a common name for all Iris species, as well as some belonging to other closely related genera.


Row {data-height=350, .tabset}
-----------------------------------------------------------------------

### Chart A

```{r}
df_a <- df %>%
  filter(Species == 'setosa')
ggplot(data = df_a,
       mapping = aes(x=Petal.Length, y=Sepal.Length)) +
  geom_point() +
  labs(title = "Setosa")
```

### Chart B

```{r}

```

### Chart C

```{r}

```

New Page
=====================================

Row {data-height=350}
-------------------------------------

Here is where my EDA table goes